### ISSUE TITLE
SLAVE flashed project (ESF-50)

### ISSUE THREAD

**Issue by pepopi1** [espressif/esp-serial-flasher#67]
Hello
First of all, this is a personal issue. I have uploaded the partition-table.bin, main.bin and bootloader.bin of a simple program that blinks a LED to the ESP32 binaries folder. However, after running the example the LED does not blink. I have also tried to restart the slave after disconnecting the cables that impede the normal booting. I am using two esp wrover b. What am I doing wrong or what am I missing?

Thank you

**Comment by dobairoland** [comment]
I'm but I'm closing this since this is issue/feature request tracker.

You might want to investigate that what it is doing. You can read back the flash content (esptool's read_flash command) and compare it with the original binaries. You can examine if anything is printed to UART. All of this can help narrow down what is happening.
